### PR TITLE
196 travis fix

### PR DESCRIPTION
**Pull request by TrevorEdwards**
Fixes https://github.com/bigredhacks/bigredhacks-web/issues/196 by removing dots from environment variables.

I've updated the travis, test, and production env variables so they should be ready to merge this.

### CODE REVIEW

**Comment by mahsu** [comment]
http://unix.stackexchange.com/questions/93532/exporting-a-variable-with-dot-in-it says that dots are not actually valid as part of the environment variable syntax. I think that heroku is actually setting the config varsPerhaps we should use a workaround.

The main reason I'm hesitating to approve this pr is that the current environment var system poses a security risk, especially to future developers who may not be familiar with the system. The json config format is namespaced but the environment var format is not, potentially causing issues when deploying when there's a naming conflict.

I think we should either remove the namespacing altogether or figure out a workaround.

**Comment by mahsu** [comment]
https://travis-ci.org/bigredhacks/bigredhacks-web/builds/158892004 passes with dot variables.

**Comment by TrevorEdwards** [comment]
I agree and I do like the namespacing. One potential fix, though not super pretty, is to just use a double _ as our new dot since _ is an allowable character according to http://stackoverflow.com/questions/2821043/allowed-characters-in-linux-environment-variable-names . Double _ since we have some single _ names in use.

**Comment by mahsu** [comment]
Yeah that sounds like it would work. I think we should document that double
underscores are to be disallowed.

**Comment by mahsu** [comment]
lgtm passing build

**Pull request merged**
